spring:
  application:
    name: cards-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://cards-db:5432/cards}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: ${DB_USER:root}
    password: ${DB_PASS:root}
    url: ${DB_URL:jdbc:postgresql://cards-db:5432/cards}
token:
  secret: ${TOKEN_SECRET:default}