spring:
  application:
    name: cards-api
  datasource:
    url: localhost:5432/
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev
