spring:
  application:
    name: cards-api
  datasource:
    url: jdbc:postgresql://localhost:5433/cards
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: root
    password: root
    url: jdbc:postgresql://localhost:5433/cards

token:
  secret: 123QWE890JSFD7s8d9fywifuah32b3kifpa9fgw