spring:
  application:
    name: cards-api
  datasource:
    url: jdbc:postgresql://localhost:5433/cards
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: jdbc:postgresql://localhost:5433/cards
    password: root
    url: root