spring:
  application:
    name: cards-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://cards-db:5432/cards}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: ${DB_USER:root}
    password: ${DB_PASS:root}
    url: ${DB_URL:jdbc:postgresql://cards-db:5432/cards}
token:
  secret: ${TOKEN_SECRET:default}
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json